language: node_js
node_js:
  - 0.10
  - 4
  - 6
  - 8
  - 10
before_install:
  - npm install -g qnit
after_success:
  - npm install -g nyc
  - npm install -g codecov
  - nyc --reporter lcov npm test && codecov
